### ISSUE TITLE
curl bug 

### ISSUE THREAD

**Issue by anyouuu** [sixpack/sixpack#291]
comand "$ curl http://localhost:5000/participate?experiment=button_color&alternatives=red&alternatives=blue&client_id=12345678-1234-5678-1234-567812345678
"

server exception :

^C----------------------------------------
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 71, in __call__
    return self.app(environ, add_cors_headers)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 92, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 101, in wsgi_app
    return response(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 1169, in __call__
    start_response(status, headers)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 56, in add_cors_headers
    get_origin(status, headers))
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 51, in get_origin
    return origin if self.origin_regexp.match(origin) else "null"
AttributeError: 'NoneType' object has no attribute 'match'

**Comment by ShaneKilkelly** [comment]
I just ran into this while setting up sixpack for local testing and evaluation. Is sixpack even maintained any more? there's an open pull request (https://github.com/sixpack/sixpack/pull/280) that fixes this issue, but it's been open since last year with no word from the maintainers.

As it stands, the setup documentation leads straight to this crash, with the current version of sixpack.

**Comment by zackkitzmiller** [comment]
Merged 280. I’ll rekease tomorrow.

**Comment by ShaneKilkelly** [comment]
Thanks @zackkitzmiller !

**Comment by Singwai** [comment]
Since this is merged. can we close this?

**Comment by ShaneKilkelly** [comment]
The code is fixed, but the sixpack package on pypi is still at 2.7.0, released last year, so the bug is still present for anyone setting up sixpack now. 

A new 2.7.x release should do it :+1: , and thanks!
