### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'match'

### ISSUE THREAD

**Issue by alastairbattrick** [sixpack/sixpack#294]
Hi

I've installed sixpack via pip on Python 2.7.5

When I send curl request to our endpoint, I get a 500 Internal Server Error, and the below error in the sixpack accesslog. However, the sixpackweb interface does show me that the request worked as the experiment appears.

example request:
host:5000/participate?experiment=test&alternatives=red&alternatives=blue&client_id=12345

Error on request:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/sixpack/server.py", line 71, in __call__
    return self.app(environ, add_cors_headers)
  File "/usr/lib64/python2.7/site-packages/sixpack/server.py", line 92, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/sixpack/server.py", line 101, in wsgi_app
    return response(environ, start_response)
  File "/usr/lib/python2.7/site-packages/werkzeug/wrappers.py", line 1169, in __call__
    start_response(status, headers)
  File "/usr/lib64/python2.7/site-packages/sixpack/server.py", line 56, in add_cors_headers
    get_origin(status, headers))
  File "/usr/lib64/python2.7/site-packages/sixpack/server.py", line 51, in get_origin
    return origin if self.origin_regexp.match(origin) else "null"
AttributeError: 'NoneType' object has no attribute 'match'
```

**Comment by alastairbattrick** [comment]
Sorry, duplicate of #280
